-- Step 2: Add rating fields to users table
ALTER TABLE public.users 
ADD COLUMN IF NOT EXISTS rating DECIMAL(2,1) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS rating_as_described DECIMAL(2,1) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS rating_timing DECIMAL(2,1) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS rating_communication DECIMAL(2,1) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS rating_cost DECIMAL(2,1) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS rating_performance DECIMAL(2,1) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS total_reviews INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS positive_reviews INTEGER DEFAULT 0;