// Figma Component Mappings
// Generated from React Native components
// Use this to map your code components to Figma designs

export const componentMappings = {
  PaymentSettings: {
    path: '/Users/Codes/izimate-job-mobile/components/settings/PaymentSettings.tsx',
    props: [],
    hasStyles: true,
    usesTheme: false,
  },
  LanguageSelector: {
    path: '/Users/Codes/izimate-job-mobile/components/settings/LanguageSelector.tsx',
    props: [],
    hasStyles: true,
    usesTheme: false,
  },
  JobCompletionModal: {
    path: '/Users/Codes/izimate-job-mobile/components/rating/JobCompletionModal.tsx',
    props: ['visible'],
    hasStyles: true,
    usesTheme: false,
  },
  RatingForm: {
    path: '/Users/Codes/izimate-job-mobile/components/rating/RatingForm.tsx',
    props: ['revieweeId'],
    hasStyles: true,
    usesTheme: false,
  },
  ExternalCalendarSync: {
    path: '/Users/Codes/izimate-job-mobile/components/calendar/ExternalCalendarSync.tsx',
    props: [],
    hasStyles: true,
    usesTheme: false,
  },
  ServiceSelector: {
    path: '/Users/Codes/izimate-job-mobile/components/calendar/ServiceSelector.tsx',
    props: [],
    hasStyles: true,
    usesTheme: false,
  },
  BookingForm: {
    path: '/Users/Codes/izimate-job-mobile/components/calendar/BookingForm.tsx',
    props: [],
    hasStyles: true,
    usesTheme: false,
  },
  CalendarStats: {
    path: '/Users/Codes/izimate-job-mobile/components/calendar/CalendarStats.tsx',
    props: [],
    hasStyles: true,
    usesTheme: false,
  },
  CalendarGrid: {
    path: '/Users/Codes/izimate-job-mobile/components/calendar/CalendarGrid.tsx',
    props: [],
    hasStyles: true,
    usesTheme: false,
  },
  EventDisplay: {
    path: '/Users/Codes/izimate-job-mobile/components/calendar/EventDisplay.tsx',
    props: [],
    hasStyles: true,
    usesTheme: false,
  },
  TimeSlotSelector: {
    path: '/Users/Codes/izimate-job-mobile/components/calendar/TimeSlotSelector.tsx',
    props: [],
    hasStyles: true,
    usesTheme: false,
  },
  UnifiedCalendar: {
    path: '/Users/Codes/izimate-job-mobile/components/calendar/UnifiedCalendar.tsx',
    props: [],
    hasStyles: true,
    usesTheme: false,
  },
  GuestCheckoutForm: {
    path: '/Users/Codes/izimate-job-mobile/components/forms/GuestCheckoutForm.tsx',
    props: ['onSubmit'],
    hasStyles: true,
    usesTheme: true,
  },
  BookingChatActions: {
    path: '/Users/Codes/izimate-job-mobile/components/chat/BookingChatActions.tsx',
    props: ['match'],
    hasStyles: true,
    usesTheme: false,
  },
  BookingMessageBubble: {
    path: '/Users/Codes/izimate-job-mobile/components/chat/BookingMessageBubble.tsx',
    props: ['message'],
    hasStyles: true,
    usesTheme: false,
  },
  BookingCalendar: {
    path: '/Users/Codes/izimate-job-mobile/components/booking/BookingCalendar.tsx',
    props: ['listingId', 'listingTitle', 'providerId', 'providerName', 'visible', 'initialDate', 'onClose', 'onBookingComplete', 'onBookingSelect', 'time', 'serviceName', 'servicePrice', 'currency', 'durationMinutes'],
    hasStyles: false,
    usesTheme: false,
  },
  CancellationPolicyDisplay: {
    path: '/Users/Codes/izimate-job-mobile/components/booking/CancellationPolicyDisplay.tsx',
    props: ['listing'],
    hasStyles: true,
    usesTheme: false,
  },
  CustomerProfile: {
    path: '/Users/Codes/izimate-job-mobile/components/booking/CustomerProfile.tsx',
    props: ['customerId', 'guestCustomerId', 'providerId', 'onBack'],
    hasStyles: true,
    usesTheme: false,
  },
  StaffManager: {
    path: '/Users/Codes/izimate-job-mobile/components/booking/StaffManager.tsx',
    props: ['providerId'],
    hasStyles: true,
    usesTheme: false,
  },
  PriceBreakdown: {
    path: '/Users/Codes/izimate-job-mobile/components/booking/PriceBreakdown.tsx',
    props: ['booking'],
    hasStyles: true,
    usesTheme: false,
  },
  BookingHistory: {
    path: '/Users/Codes/izimate-job-mobile/components/booking/BookingHistory.tsx',
    props: ['userId'],
    hasStyles: true,
    usesTheme: false,
  },
  CalendarIntegration: {
    path: '/Users/Codes/izimate-job-mobile/components/booking/CalendarIntegration.tsx',
    props: ['userId', 'listingId', 'onConnectionChange', 'onBookDate'],
    hasStyles: true,
    usesTheme: false,
  },
  QuickCustomerRegistration: {
    path: '/Users/Codes/izimate-job-mobile/components/booking/QuickCustomerRegistration.tsx',
    props: ['userId'],
    hasStyles: true,
    usesTheme: false,
  },
  GuestCheckout: {
    path: '/Users/Codes/izimate-job-mobile/components/booking/GuestCheckout.tsx',
    props: ['listing'],
    hasStyles: true,
    usesTheme: false,
  },
  InAppBookingCalendar: {
    path: '/Users/Codes/izimate-job-mobile/components/booking/InAppBookingCalendar.tsx',
    props: ['listing', 'provider', 'onBookingSelect', 'time', 'serviceName', 'servicePrice', 'currency', 'durationMinutes'],
    hasStyles: true,
    usesTheme: false,
  },
  ClientBookingPortal: {
    path: '/Users/Codes/izimate-job-mobile/components/booking/ClientBookingPortal.tsx',
    props: ['userId'],
    hasStyles: true,
    usesTheme: false,
  },
  CalendarView: {
    path: '/Users/Codes/izimate-job-mobile/components/booking/CalendarView.tsx',
    props: ['userId', 'listingId', 'onDateSelect', 'onEventPress', 'onBookDate'],
    hasStyles: true,
    usesTheme: false,
  },
  BiometricBookingConfirmation: {
    path: '/Users/Codes/izimate-job-mobile/components/booking/BiometricBookingConfirmation.tsx',
    props: ['serviceName', 'lat', 'lng'],
    hasStyles: true,
    usesTheme: false,
  },
  CouponManager: {
    path: '/Users/Codes/izimate-job-mobile/components/booking/CouponManager.tsx',
    props: ['providerId', 'listingId'],
    hasStyles: true,
    usesTheme: false,
  },
  MyBookingsCalendar: {
    path: '/Users/Codes/izimate-job-mobile/components/booking/MyBookingsCalendar.tsx',
    props: ['userId', 'viewType'],
    hasStyles: true,
    usesTheme: false,
  },
  RevenueReports: {
    path: '/Users/Codes/izimate-job-mobile/components/booking/RevenueReports.tsx',
    props: ['providerId', 'listingId'],
    hasStyles: true,
    usesTheme: false,
  },
  RecurringBookingForm: {
    path: '/Users/Codes/izimate-job-mobile/components/booking/RecurringBookingManager.tsx',
    props: ['visible', 'onClose', 'onConfirm', 'recurrenceEndDate', 'numberOfOccurrences'],
    hasStyles: true,
    usesTheme: false,
  },
  QuickEventForm: {
    path: '/Users/Codes/izimate-job-mobile/components/booking/QuickEventForm.tsx',
    props: ['visible', 'onClose', 'selectedDate', 'userId', 'viewType', 'onEventCreated'],
    hasStyles: true,
    usesTheme: false,
  },
  CustomerManagement: {
    path: '/Users/Codes/izimate-job-mobile/components/booking/CustomerManagement.tsx',
    props: ['userId'],
    hasStyles: true,
    usesTheme: false,
  },
  UnifiedBookingsTab: {
    path: '/Users/Codes/izimate-job-mobile/components/booking/UnifiedBookingsTab.tsx',
    props: ['userId'],
    hasStyles: false,
    usesTheme: false,
  },
  BookingDetails: {
    path: '/Users/Codes/izimate-job-mobile/components/booking/BookingDetails.tsx',
    props: ['booking'],
    hasStyles: true,
    usesTheme: false,
  },
  QuickEventForm: {
    path: '/Users/Codes/izimate-job-mobile/components/booking/QuickEventFormNew.tsx',
    props: ['visible', 'onClose', 'selectedDate', 'userId', 'viewType', 'onEventCreated'],
    hasStyles: true,
    usesTheme: false,
  },
  WaitlistManager: {
    path: '/Users/Codes/izimate-job-mobile/components/booking/WaitlistManager.tsx',
    props: ['providerId', 'listingId', 'isProvider'],
    hasStyles: true,
    usesTheme: false,
  },
  BusinessBookingsTab: {
    path: '/Users/Codes/izimate-job-mobile/components/booking/BusinessBookingsTab.tsx',
    props: ['userId'],
    hasStyles: true,
    usesTheme: false,
  },
  BusinessAnalytics: {
    path: '/Users/Codes/izimate-job-mobile/components/booking/BusinessAnalytics.tsx',
    props: ['userId'],
    hasStyles: true,
    usesTheme: false,
  },
  BookingCalendarWidget: {
    path: '/Users/Codes/izimate-job-mobile/components/booking/BookingCalendarWidget.tsx',
    props: ['userId', 'onBookingPress'],
    hasStyles: true,
    usesTheme: false,
  },
  BlockedTimeManager: {
    path: '/Users/Codes/izimate-job-mobile/components/booking/BlockedTimeManager.tsx',
    props: ['providerId', 'listingId'],
    hasStyles: true,
    usesTheme: false,
  },
  QuickRebookingWidget: {
    path: '/Users/Codes/izimate-job-mobile/components/booking/QuickRebookingWidget.tsx',
    props: ['userId'],
    hasStyles: true,
    usesTheme: false,
  },
  BookingFlowManager: {
    path: '/Users/Codes/izimate-job-mobile/components/booking/BookingFlowManager.tsx',
    props: ['listing'],
    hasStyles: true,
    usesTheme: false,
  },
  TrustSignals: {
    path: '/Users/Codes/izimate-job-mobile/components/booking/TrustSignals.tsx',
    props: ['provider'],
    hasStyles: true,
    usesTheme: false,
  },
  LocationPickerMap: {
    path: '/Users/Codes/izimate-job-mobile/components/location/LocationPickerMap.native.tsx',
    props: ['onLocationSelect'],
    hasStyles: false,
    usesTheme: false,
  },
  LocationPickerMapBase: {
    path: '/Users/Codes/izimate-job-mobile/components/location/LocationPickerMap.base.tsx',
    props: ['onLocationSelect'],
    hasStyles: true,
    usesTheme: false,
  },
  LocationPickerMap: {
    path: '/Users/Codes/izimate-job-mobile/components/location/LocationPickerMap.tsx',
    props: ['onLocationSelect'],
    hasStyles: false,
    usesTheme: false,
  },
  ListingCard: {
    path: '/Users/Codes/izimate-job-mobile/components/listings/ListingCard.tsx',
    props: ['listing'],
    hasStyles: true,
    usesTheme: false,
  },
  Step4Review: {
    path: '/Users/Codes/izimate-job-mobile/components/listings/steps/Step4Review.tsx',
    props: ['formState'],
    hasStyles: true,
    usesTheme: false,
  },
  Step3Location: {
    path: '/Users/Codes/izimate-job-mobile/components/listings/steps/Step3Location.tsx',
    props: ['formState'],
    hasStyles: true,
    usesTheme: false,
  },
  Step5Booking: {
    path: '/Users/Codes/izimate-job-mobile/components/listings/steps/Step5Booking.tsx',
    props: ['formData', 'onUpdate', 'onNext', 'onBack', 'isLoading'],
    hasStyles: false,
    usesTheme: false,
  },
  Step2Budget: {
    path: '/Users/Codes/izimate-job-mobile/components/listings/steps/Step2Budget.tsx',
    props: ['formState'],
    hasStyles: true,
    usesTheme: false,
  },
  Step1BasicInfo: {
    path: '/Users/Codes/izimate-job-mobile/components/listings/steps/Step1BasicInfo.tsx',
    props: ['formState'],
    hasStyles: true,
    usesTheme: false,
  },
  Step5BookingSimplified: {
    path: '/Users/Codes/izimate-job-mobile/components/listings/steps/Step5BookingSimplified.tsx',
    props: ['formState', 'formActions', 'isLoading'],
    hasStyles: true,
    usesTheme: false,
  },
  Step6Settings: {
    path: '/Users/Codes/izimate-job-mobile/components/listings/steps/Step6Settings.tsx',
    props: ['formState'],
    hasStyles: true,
    usesTheme: false,
  },
  CardContainer: {
    path: '/Users/Codes/izimate-job-mobile/components/swipe/CardContainer.tsx',
    props: ['listings'],
    hasStyles: true,
    usesTheme: false,
  },
  CardDisplay: {
    path: '/Users/Codes/izimate-job-mobile/components/swipe/CardDisplay.tsx',
    props: ['listings'],
    hasStyles: true,
    usesTheme: false,
  },
  CalendarWidget: {
    path: '/Users/Codes/izimate-job-mobile/components/dashboard/CalendarWidget.tsx',
    props: ['events'],
    hasStyles: true,
    usesTheme: false,
  },
  SettingsTab: {
    path: '/Users/Codes/izimate-job-mobile/components/dashboard/SettingsTab.tsx',
    props: [],
    hasStyles: true,
    usesTheme: false,
  },
  CollapsibleSection: {
    path: '/Users/Codes/izimate-job-mobile/components/dashboard/CollapsibleSection.tsx',
    props: ['title'],
    hasStyles: true,
    usesTheme: false,
  },
  BottomTabBar: {
    path: '/Users/Codes/izimate-job-mobile/components/dashboard/BottomTabBar.tsx',
    props: ['tabs'],
    hasStyles: true,
    usesTheme: false,
  },
  BookingManagementTab: {
    path: '/Users/Codes/izimate-job-mobile/components/dashboard/BookingManagementTab.tsx',
    props: [],
    hasStyles: false,
    usesTheme: false,
  },
  ApprovalsTab: {
    path: '/Users/Codes/izimate-job-mobile/components/dashboard/ApprovalsTab.tsx',
    props: [],
    hasStyles: true,
    usesTheme: false,
  },
  LikedTab: {
    path: '/Users/Codes/izimate-job-mobile/components/dashboard/LikedTab.tsx',
    props: [],
    hasStyles: true,
    usesTheme: false,
  },
  VerificationTabEnhanced: {
    path: '/Users/Codes/izimate-job-mobile/components/dashboard/VerificationTabEnhanced.tsx',
    props: [],
    hasStyles: true,
    usesTheme: false,
  },
  AffiliateTab: {
    path: '/Users/Codes/izimate-job-mobile/components/dashboard/AffiliateTab.tsx',
    props: [],
    hasStyles: true,
    usesTheme: false,
  },
  BillingTab: {
    path: '/Users/Codes/izimate-job-mobile/components/dashboard/BillingTab.tsx',
    props: [],
    hasStyles: true,
    usesTheme: false,
  },
  ListingsTab: {
    path: '/Users/Codes/izimate-job-mobile/components/dashboard/ListingsTab.tsx',
    props: [],
    hasStyles: true,
    usesTheme: false,
  },
  TabBar: {
    path: '/Users/Codes/izimate-job-mobile/components/dashboard/TabBar.tsx',
    props: ['tabs'],
    hasStyles: true,
    usesTheme: false,
  },
  VerificationTab: {
    path: '/Users/Codes/izimate-job-mobile/components/dashboard/VerificationTab.tsx',
    props: [],
    hasStyles: true,
    usesTheme: false,
  },
  SkeletonLoader: {
    path: '/Users/Codes/izimate-job-mobile/components/common/SkeletonLoader.tsx',
    props: ['type', 'count'],
    hasStyles: true,
    usesTheme: false,
  },
  BottomSheetExample: {
    path: '/Users/Codes/izimate-job-mobile/components/common/BottomSheetExample.tsx',
    props: ['visible', 'onClose', 'title', 'children', 'snapPoints'],
    hasStyles: true,
    usesTheme: false,
  },
  RatingCriteria: {
    path: '/Users/Codes/izimate-job-mobile/components/profile/RatingCriteria.tsx',
    props: ['ratings'],
    hasStyles: true,
    usesTheme: false,
  },
  ClientProfileEnhanced: {
    path: '/Users/Codes/izimate-job-mobile/components/profile/ClientProfileEnhanced.tsx',
    props: ['customerId'],
    hasStyles: true,
    usesTheme: false,
  },
  NotificationCenter: {
    path: '/Users/Codes/izimate-job-mobile/components/notifications/NotificationCenter.tsx',
    props: [],
    hasStyles: true,
    usesTheme: false,
  },
  NotificationSettings: {
    path: '/Users/Codes/izimate-job-mobile/components/notifications/NotificationSettings.tsx',
    props: [],
    hasStyles: true,
    usesTheme: false,
  },
  NotificationBell: {
    path: '/Users/Codes/izimate-job-mobile/components/notifications/NotificationBell.tsx',
    props: [],
    hasStyles: true,
    usesTheme: false,
  },
  ReviewWithIncentive: {
    path: '/Users/Codes/izimate-job-mobile/components/reviews/ReviewWithIncentive.tsx',
    props: ['revieweeId', 'revieweeName', 'bookingId', 'serviceType', 'visible', 'onClose', 'onSubmitted'],
    hasStyles: true,
    usesTheme: false,
  },
  ReviewIncentiveSettings: {
    path: '/Users/Codes/izimate-job-mobile/components/reviews/ReviewIncentiveSettings.tsx',
    props: ['providerId', 'listingId'],
    hasStyles: true,
    usesTheme: false,
  },
  ReviewPlatformSelector: {
    path: '/Users/Codes/izimate-job-mobile/components/reviews/ReviewPlatformSelector.tsx',
    props: ['bookingId'],
    hasStyles: true,
    usesTheme: false,
  },
  ExternalReviewsManager: {
    path: '/Users/Codes/izimate-job-mobile/components/reviews/ExternalReviewsManager.tsx',
    props: ['providerId', 'listingId'],
    hasStyles: true,
    usesTheme: false,
  },
}

// Usage in Figma:
// 1. Create design components in Figma matching these names
// 2. Use Code Connect to link Figma components to code paths
// 3. Use MCP server to generate designs from code
